version: '0.2'
language: en
ignorePaths:
  - '**/node_modules/**'
  - '**/vscode_extension/**'
  - '**/.git/**'
  - '**/.pnpm-lock.json'
  - '**/pnpm-lock.yaml'
  - '**/yarn.lock'
  - .vscode
  - 'package-lock.json'
  - 'megalinter-reports'
  - '.devcontainer/.dockerignore'
  - .gitattributes
  - .gitignore
  - '.github/actions/spelling/**'
  - '.github/labels.yml'
  - '.github/pr-labeler.yml'
  - .prettierignore
  - .tfignore
  - CHANGELOG.md
  - LICENSE
  - LICENSES/**
  - cspell.config.yaml
files:
  - .github/**/*.{md,txt,yaml,yml}
  - .git/COMMIT_EDITMSG
  - docs/**/**
  - scripts/**
  - jmbde/**
  - jmbdeTests/**
  - jmbdeUITests/**
words:
  - Jürgen
  - Mülbert
  - jmuelbert
  - Aglolia
  - Akka
  - adoc
  - ambientale
  - Anleitungens
  - aqui
  - Astro
  - astrodotbuild
  - astrojs
  - Autobuild
  - autolabeler
  - automerge
  - Bazel
  - Beginne
  - Bitstream
  - blinkmacsystemfont
  - buildscript
  - Codecov
  - Codacy
  - CODEOWNERS
  - Colab
  - Comienza
  - commitlint
  - COMMIT_EDITMSG
  - Cuda
  - codeql
  - culori
  - Configuración
  - consts
  - dessant
  - devskim
  - Deutsch
  - devcontainer
  - devcontainers
  - Diátaxis
  - docsearch
  - docsify
  - Documentación
  - Docus
  - DUPS
  - Ecograder
  - ecológica
  - Ecoping
  - Einrichtung
  - Empezando
  - Erste
  - FOUC
  - frontmatter
  - fsfe
  - focusable
  - ghaction
  - gittools
  - goodcheck
  - gsoc
  - Guías
  - hastscript
  - hier
  - Impatto
  - Inizia
  - Iniziamo
  - Italiano
  - labelledby
  - lengthframeencoder
  - Manuelle
  - Markdoc
  - matthiashermsen
  - MSDO
  - mshick
  - Nextra
  - nocheck
  - OSSAR
  - ossf
  - outreachy
  - Poulain
  - preact
  - Preacts
  - rarr
  - recvbuffer
  - refact
  - Referencias
  - Referenz
  - rehype
  - resx
  - returntocorp
  - Riferimenti
  - rubocop
  - ruleset
  - Sarif
  - Schritte
  - Screenreader
  - searchbox
  - Semgrep
  - Signup
  - skiplink
  - sobolevn
  - srggrs
  - stefanzweifel
  - stylecop
  - stylelint
  - stylelintignore
  - tomwhross
  - tsconfigs
  - Umweltbelastung
  - Unported
  - wagoid
  - WCAG
  - webfont
  - withastro
flagWords:
  - hte
maxNumberOfProblems: 1000
import: []
useGitignore: true
overrides:
  - filename: '**/de_DE/**'
    language: en,de
  - filename: '**/nl_NL/**'
    language: en,nl
  - filename: '**/ru_RU/samples/**'
    language: ru,en
  - filename: '**/sv/**'
    language: en,sv
  - filename: 'package.json'
    ignoreWords:
      - colour
      - canot
cache:
  useCache: true
  cacheStrategy: content
enableFiletypes:
  - shellscript
dictionaryDefinitions:
  - name: ./project-words
    addWords: true
    scope:
      - workspace
    path: ./project-words.txt
dictionaries:
  - ./project-words
  - bash
  - companies
  - csharp
  - css
  - filetypes
  - fonts
  - misc
  - node
  - npm
  - powershell
  - python
  - software-terms
  - typescript
