#!/bin/bash -eux

set -o pipefail
echo "Set the env"
export FRAMEWORK_NAME="JMBeData"
export SCHEME="JMBeData"
export SDK="macosx14.0"
export DESTINATION="arch=x86_64"
export SWIFT_VERSION="5.1"
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
export UPDATE_DOCS="true"
export EXPANDED_CODE_SIGN_IDENTITY="-"
export EXPANDED_CODE_SIGN_IDENTITY_NAME="-"
mkdir -p build
echo "Install dependencies"
xcodebuild -version
xcodebuild -showsdks
echo "build the app"
xcodebuild -project "$FRAMEWORK_NAME.xcodeproj" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build test -verbose | xcpretty -c
echo "steps after the build"
prettier -w "**"
cspell
swiftlint lint
swift-format lint --color-diagnostics  --recursive JMBeData
swift-format lint --color-diagnostics  --recursive JMBeDataTest
swift-format lint --color-diagnostics  --recursive JMBeDataUITests
jazzy
rubocop
slather

scripts/validate-markdown.sh
