---
# SPDX-FileCopyrightText: Jürgen Mülbert
#
# SPDX-License-Identifier: MIT

name: "Misspell fixer"

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  misspell-fixer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "🧰 Check out code"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Misspell Fixer
        uses: sobolevn/misspell-fixer-action@v0

      - name: Check for changes
        run: git diff --exit-code ${{ github.sha }}

      - name: Create Pull Request for typos
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Fix typos by misspell-fixer"
          title: "Fix typos by misspell-fixer for ${{ github.ref }}"
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          branch: "auto-pr/misspell-fixer/${{ github.ref }}"
