---
# SPDX-FileCopyrightText: Alex Page
#
# SPDX-License-Identifier: MIT

name: Move new issues into Triage

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move Issue to Triage Column
        uses: alex-page/github-project-automation-plus@v0
        with:
          project: anniversaryreminder
          column: Triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
