---
# SPDX-FileCopyrightText: Jef LeCompte
#
# SPDX-License-Identifier: MIT
#
name: Pull Request Linter
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-pull-request-title:
    name: Lint pull request title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: '🧰 Check out code'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Lint pull request title
        uses: matthiashermsen/lint-pull-request-title@v1
        with:
          allowed-pull-request-types: chore,feat,fix
