---
# SPDX-FileCopyrightText: Jürgen Mülbert <juergen.muelbert@web.de>
#
# SPDX-License-Identifier: EUPL-1.2

name: REUSE Compliance Check

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main", "develop", "release"]

  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can
    # default to all as well
    types: [opened, reopened, synchronize]
    # pull_request_target event is required for autolabeler to
    # support PRs from forks
    # pull_request_target:

permissions:
  contents: read

jobs:
  ReuseCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "🧰 Check out code"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v2
