---
# Name of this GitHub Actions workflow.
name: Semgrep

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

  schedule:
    - cron: "22 17 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    container:
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "🧰 Check out code"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

        # Skip any PR created by dependabot to avoid permission issues;
        if: (github.actor != 'dependabot[bot]')

      - name: Run semgrep ci
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac
        with:
          sarif_file: semgrep.sarif
        if: always()
