---
  # SPDX-FileCopyrightText: Jürgen Mülbert <juergen.muelbert@outlook.de>
  #
  # SPDX-License-Identifier: EUPL-1.2
  #

  name: Triage Issues

  on: # yamllint disable-line rule:truthy
    push:
      branches-ignore:
        - dependabot/**
    issue_comment:
      types:
        - created
        - edited

    schedule:
      - cron: "0 0 * * *"

  permissions:
    issues: write
    pull-requests: write

  concurrency:
    group: triage-issues
    cancel-in-progress: ${{ github.event_name != 'issue_comment' }}

  jobs:
    stale:
      if: |
        startsWith(github.repository, 'jmuelbert/') &&
        (
          !startsWith(github.event.repository.name, 'dependabot/') ||
          (github.event_name == 'schedule') ||
          (
            contains(github.event.issue.labels.*.name, 'stale') ||
            contains(github.event.pull_request.labels.*.name, 'stale')
          )
        )
      runs-on: ubuntu-latest
      steps:
        - name: Mark or Close Stale Issues and Pull Requests
          uses: actions/stale@v8
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            days-before-stale: 365
            days-before-close: 30
            stale-issue-message: |
              This issue was automatically marked as deprecated because there has been no activity for quite some time. It will be closed if there is no further activity.
            stale-pr-message: |
              This pull request was automatically marked as deprecated because it hasn't had any activity in quite some time. It will be closed if there is no further activity.
            exempt-issue-labels: "gsoc-outreachy, help wanted, in progress"
            exempt-pr-labels: "gsoc-outreachy, help wanted, in progress"

    bump-pr-stale:
      if: |
        startsWith(github.repository, 'jmuelbert/') &&
        (
          !startsWith(github.event.repository.name, 'dependabot/') ||
          (github.event_name == 'schedule') ||
          (
            contains(github.event.issue.labels.*.name, 'stale') ||
            contains(github.event.pull_request.labels.*.name, 'stale')
          )
        )
      runs-on: ubuntu-latest
      steps:
        - name: Mark or Close Stale `bump-formula-pr` and `bump-cask-pr` Pull Requests
          uses: actions/stale@v8
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            days-before-stale: 2
            days-before-close: 1
            stale-pr-message: |
              This pull request was automatically marked as deprecated because it hasn't had any activity in quite some time. It will be closed if there is no further activity. To keep this pull request open, add a 'help wanted' or 'in progress' label.          exempt-pr-labels: "help wanted, in progress"
            any-of-labels: "bump-formula-pr, bump-cask-pr"

    lock-threads:
      if: startsWith(github.repository, 'jmuelbert/') && github.event_name != 'issue_comment'
      runs-on: ubuntu-latest

      steps:
        - name: Lock Outdated Threads
          uses: dessant/lock-threads@v4
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            issue-inactive-days: 30
            add-issue-labels: outdated
            pr-inactive-days: 30
            add-pr-labels: outdated
